; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Mega Man 2:
; FAMISTUDIO_USE_VOLUME_TRACK = 1

.export _music_data_mega_man_2:=music_data_mega_man_2

music_data_mega_man_2:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : Dr. Wily's Castle
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Enemy Robot Selected
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_mega_man_2
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env9,@env12,@env0 ; 00 : WilyNoiseDrumHi
	.word @env16,@env9,@env12,@env0 ; 01 : WilyNoiseDrumLo
	.word @env17,@env9,@env13,@env0 ; 02 : WilyLeadDuty2
	.word @env5,@env9,@env12,@env0 ; 03 : StageBass
	.word @env5,@env8,@env12,@env0 ; 04 : StageBassPow
	.word @env5,@env9,@env12,@env0 ; 05 : WilyBass
	.word @env7,@env9,@env15,@env0 ; 06 : WilyLeadDuty1
	.word @env6,@env9,@env12,@env0 ; 07 : WilyLeadDuty0
	.word @env5,@env19,@env12,@env0 ; 08 : WilyBassPow
	.word @env6,@env9,@env15,@env0 ; 09 : WilyLeadDuty1Alt
	.word @env6,@env9,@env1,@env11 ; 0a : WilyLeadDuty3Tremolo
	.word @env18,@env9,@env12,@env0 ; 0b : StageLead
	.word @env14,@env9,@env12,@env0 ; 0c : StageLeadAlt
	.word @env18,@env9,@env12,@env2 ; 0d : StageLeadTremolo
	.word @env18,@env9,@env15,@env0 ; 0e : StageLead2
	.word @env18,@env9,@env15,@env3 ; 0f : StageLead2Tremolo
	.word @env6,@env9,@env12,@env11 ; 10 : WilyLeadDuty0Tremolo
	.word @env6,@env9,@env15,@env11 ; 11 : WilyLeadDuty1Tremolo
	.word @env5,@env9,@env12,@env4 ; 12 : StageBassTremolo

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $00,$bd,$bb,$bd,$c0,$c3,$c6,$c3,$c0,$00,$01
@env3:
	.byte $00,$bd,$ba,$bd,$c3,$c6,$c3,$c0,$00,$01
@env4:
	.byte $00,$bc,$b9,$bc,$bf,$c2,$c5,$c2,$bf,$00,$01
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $00,$cf,$13,$cd,$13,$ca,$00,$05
@env7:
	.byte $00,$ce,$02,$cd,$03,$cc,$03,$cb,$03,$ca,$03,$c9,$03,$c8,$03,$c7,$00,$0f
@env8:
	.byte $c0,$bd,$bb,$b9,$b8,$b6,$b5,$b4,$b3,$b2,$00,$09
@env9:
	.byte $c0,$7f,$00,$01
@env10:
	.byte $00,$cf,$c5,$c5,$c0,$00,$04
@env11:
	.byte $00,$c1,$c0,$bf,$c1,$00,$02
@env12:
	.byte $7f,$00,$00
@env13:
	.byte $c2,$7f,$00,$00
@env14:
	.byte $00,$c0,$ca,$c2,$00,$01
@env15:
	.byte $c1,$7f,$00,$00
@env16:
	.byte $00,$cf,$cf,$cb,$02,$c7,$02,$c3,$c0,$00,$08
@env17:
	.byte $00,$cf,$0e,$ce,$0e,$cd,$0e,$cc,$00,$07
@env18:
	.byte $00,$c0,$ca,$00,$02
@env19:
	.byte $c0,$c0,$be,$be,$bc,$bc,$bb,$00,$06

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $8c, $1a
@song0ref7:
	.byte $8f, $00
@song0ref9:
	.byte $1d, $85, $00, $1d, $85, $00, $1d, $8f, $00, $1d, $85, $00, $1d, $85, $00, $1d, $8f, $00, $1a, $8f, $00, $93, $1a, $85
	.byte $00, $1a, $85, $00, $1d, $8f, $00, $1d, $85, $00, $1d, $85, $00, $1d, $8f, $00, $1a, $8f, $00, $93, $21, $8f, $00, $1f
	.byte $8f, $00, $21, $8f, $00, $48
@song0ref63:
	.byte $93, $1d, $85, $00, $1d, $85, $00, $1d, $8f, $00, $1d, $85, $00, $1d, $85, $00, $1d, $8f, $00, $1a, $8f, $00, $93, $21
	.byte $8f, $00, $93, $1f, $8f, $00, $93, $1d, $8f, $00, $93, $1f, $8f, $00, $a7, $48
@song0ref103:
	.byte $93, $1f, $85, $00, $1f, $85, $00, $1f, $8f, $00, $1f, $85, $00, $1f, $85, $00, $1f, $8f, $00, $1c, $8f, $00, $93, $21
	.byte $8f, $00, $93, $1f, $8f, $00, $93, $1d, $8f, $00, $93, $1c, $8f, $00, $93
@song0ref142:
	.byte $1a, $8f, $00, $48
@song0ref146:
	.byte $93, $1a, $8f, $00, $21, $8f, $00, $24, $8f, $00, $23, $b7, $00, $1a, $8f, $00, $93, $1a, $8f, $00, $21, $8f, $00, $24
	.byte $8f, $00, $23, $8f, $00, $93, $28, $8f, $00, $29, $8f, $00, $48, $93
	.byte $41, $a4
	.word @song0ref9
@song0ref187:
	.byte $24, $8f, $00, $84, $26, $91, $48, $26, $a5, $26, $cb, $00, $24, $8f, $00, $29, $a3, $00, $26, $a3, $00, $24, $a3, $00
	.byte $26, $a3, $00, $93, $48, $24, $cb, $00, $24, $8f, $00, $26, $b7, $00, $21, $8f, $00, $22, $8f, $00, $21, $8f, $00, $1d
	.byte $8f, $00, $93, $1d, $8f, $00, $21, $8f, $00, $24, $8f, $00, $48, $26, $f3, $00, $24, $8f, $00, $29, $a3, $00, $26, $a3
	.byte $00, $24, $a3, $00, $26, $a3, $00, $24, $91, $48, $24, $cb, $00, $24, $8f, $00, $21, $8f, $00, $24, $8f, $00, $25, $8f
	.byte $00, $93, $25, $8f, $00, $25, $8f, $00, $28, $8f, $00, $2d, $cb, $00, $48, $a0, $15, $f3, $00, $13, $8f, $00, $18, $a3
	.byte $00, $16, $a3, $00, $15, $a3, $00, $16, $a3, $00, $15, $91, $48, $15, $cd, $15, $a3, $00, $13, $8f, $00, $18, $a3, $00
	.byte $16, $a3, $00, $15, $a3, $00, $16, $a3, $00, $11, $91, $48, $11, $cb, $00, $11, $8f, $00, $13, $8f, $00, $15, $8f, $00
	.byte $10, $ff, $9b, $00, $84
	.byte $41, $21
	.word @song0ref142
	.byte $24, $8f, $00, $94, $26, $91, $48, $26, $cb, $00, $26, $a3, $00, $24, $8f, $00, $26, $8f, $00, $93, $29, $b7, $00, $2d
	.byte $8f, $00, $2b, $8f, $00, $29, $8f, $00, $28, $8f, $00, $48, $26, $cb, $00, $26, $a3, $00, $24, $8f, $00, $26, $8f, $00
	.byte $93, $29, $b7, $00, $29, $8f, $00, $2b, $8f, $00, $29, $a3, $00, $48, $28, $cb, $00, $28, $8f, $00, $26, $8f, $00, $24
	.byte $8f, $00, $2d, $b7, $00, $2b, $a3, $00, $29, $a3, $00, $28, $a3, $00, $48, $28, $8f, $00, $29, $8f, $00, $28, $8f, $00
	.byte $26, $cb, $00, $1a, $8f, $00, $93, $1a, $8f, $00, $21, $8f, $00, $24, $8f, $00, $23, $8f, $00, $93
	.byte $41, $67
	.word @song0ref187
	.byte $b7, $00, $92
@song0ref485:
	.byte $1d, $8f, $00, $48, $93, $1d, $8f, $00, $1d, $8f, $00, $1c, $8f, $00, $1d, $a3, $00, $26, $8f, $00, $24, $a3, $00, $22
	.byte $a3, $00, $21, $a3, $00, $1f, $a3, $00, $1f, $8f, $00, $48, $93, $21, $8f, $00, $21, $8f, $00, $93, $21, $8f, $00, $a7
	.byte $1f, $8f, $00, $93, $21, $8f, $00, $21, $8f, $00, $93, $21, $8f, $00, $93, $1f, $8f, $00
	.byte $41, $1f
	.word @song0ref485
	.byte $93, $48, $1c, $8f, $00, $1d, $8f, $00, $1c, $8f, $00, $1a, $91, $1a, $cb, $00, $ff, $9f, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $7b, $93, $8c
@song0ref579:
	.byte $1a, $85, $00, $1a, $85, $00, $1a, $8f, $00, $1a, $85, $00, $1a, $85, $00, $1a, $8f, $00, $15, $8f, $00, $93, $15, $85
	.byte $00, $15, $85, $00, $1a, $8f, $00, $1a, $85, $00, $1a, $85, $00, $1a, $8f, $00, $15, $8f, $00, $93, $1d, $8f, $00, $1c
	.byte $8f, $00, $1d, $8f, $00, $93, $1a, $85, $00, $1a, $85, $00, $1a, $8f, $00, $1a, $85, $00, $1a, $85, $00, $1a, $8f, $00
	.byte $15, $8f, $00, $93, $1d, $8f, $00, $93, $1c, $8f, $00, $93, $1a, $8f, $00, $93, $1c, $8f, $00, $a7, $93, $1c, $85, $00
	.byte $1c, $85, $00, $1c, $8f, $00, $1c, $85, $00, $1c, $85, $00, $1c, $8f, $00, $18, $8f, $00, $93, $1d, $8f, $00, $93, $1c
	.byte $8f, $00, $93, $1a, $8f, $00, $93, $18, $8f, $00, $a7, $1a, $8f, $00
	.byte $41, $1d
	.word @song0ref146
	.byte $24, $8f, $00, $26, $8f, $00, $93
	.byte $41, $86
	.word @song0ref579
	.byte $41, $1d
	.word @song0ref146
	.byte $24, $8f, $00, $26, $8f, $00, $89, $84
@song0ref737:
	.byte $26, $91, $26, $a5, $26, $cb, $00, $24, $8f, $00, $29, $a3, $00, $26, $a3, $00, $24, $a3, $00, $26, $9b, $87, $00, $93
	.byte $24, $cb, $00, $24, $8f, $00, $26, $b7, $00, $21, $8f, $00, $22, $8f, $00, $21, $8f, $00, $1d, $8f, $00, $93, $1d, $8f
	.byte $00, $21, $87, $87, $00, $24, $8f, $00, $26, $f3, $00, $24, $8f, $00, $29, $a3, $00, $26, $a3, $00, $24, $a3, $00, $26
	.byte $9b, $87, $00, $24, $91, $24, $cb, $00, $24, $8f, $00, $21, $8f, $00, $24, $8f, $00, $25, $8f, $00, $93, $25, $8f, $00
	.byte $25, $8f, $00, $28, $8f, $00, $2d, $a5, $2d, $87, $8e, $2d
	.byte $41, $37
	.word @song0ref7
	.byte $41, $27
	.word @song0ref63
	.byte $41, $26
	.word @song0ref103
	.byte $a7, $84, $1a, $8f, $00
	.byte $41, $1d
	.word @song0ref146
	.byte $2b, $8f, $00, $2d, $8f, $00, $93, $8e
	.byte $41, $35
	.word @song0ref9
	.byte $41, $27
	.word @song0ref63
	.byte $41, $27
	.word @song0ref103
	.byte $84, $1a, $8f, $00, $93, $1a, $8f, $00, $21, $8f, $00, $24, $8f, $00, $23, $cb, $00, $1a, $8f, $00, $93, $1a, $8f, $00
	.byte $21, $8f, $00, $24, $8f, $00, $23, $8f, $00, $2b, $8f, $00, $2d, $8f, $00, $89
	.byte $41, $66
	.word @song0ref737
	.byte $9d, $a2
@song0ref924:
	.byte $1a, $8f, $00, $93, $1a, $8f, $00, $1a, $8f, $00, $18, $8f, $00, $1a, $a3, $00, $22, $8f, $00, $1f, $a3, $00, $1f, $a3
	.byte $00, $1d, $a3, $00, $1c, $a3, $00, $1c, $8f, $00, $93, $1d, $8f, $00, $1d, $8f, $00, $93, $1d, $8f, $00, $a7, $1c, $8f
	.byte $00, $93, $1d, $8f, $00, $1d, $8f, $00, $93, $1d, $8f, $00, $93, $1c, $8f, $00
	.byte $41, $1f
	.word @song0ref924
	.byte $93, $18, $8f, $00, $1a, $8f, $00, $18, $8f, $00, $15, $91, $15, $cb, $00, $ff, $9f, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $8a
@song0ref1013:
	.byte $26, $8f, $00
@song0ref1016:
	.byte $26, $85, $00, $26, $85, $00, $26, $8f, $00, $26, $85, $00, $26, $85, $00, $26, $8f, $00, $26, $85, $00, $26, $85, $00
	.byte $26, $8f, $00, $26, $85, $00, $26, $85, $00
	.byte $41, $24
	.word @song0ref1013
@song0ref1052:
	.byte $22, $8f, $00, $22, $85, $00, $22, $85, $00, $22, $8f, $00, $22, $85, $00, $22, $85, $00, $22, $8f, $00, $22, $85, $00
	.byte $22, $85, $00, $22, $8f, $00, $22, $85, $00, $22, $85, $00
	.byte $41, $24
	.word @song0ref1052
@song0ref1091:
	.byte $24, $8f, $00, $24, $85, $00, $24, $85, $00, $24, $8f, $00, $24, $85, $00, $24, $85, $00, $24, $8f, $00, $24, $85, $00
	.byte $24, $85, $00, $24, $8f, $00, $24, $85, $00, $24, $85, $00
	.byte $41, $24
	.word @song0ref1091
	.byte $41, $24
	.word @song0ref1013
@song0ref1133:
	.byte $26, $8f, $00, $26, $85, $00, $26, $85, $00, $26, $8f, $00, $26, $85, $00, $26, $85, $00, $26, $8f, $00, $26, $85, $00
	.byte $26, $85, $00, $24, $8f, $00, $26, $91, $8b, $00, $85
	.byte $41, $21
	.word @song0ref1016
	.byte $41, $24
	.word @song0ref1013
	.byte $41, $24
	.word @song0ref1052
	.byte $41, $24
	.word @song0ref1052
	.byte $41, $24
	.word @song0ref1091
	.byte $41, $24
	.word @song0ref1091
	.byte $41, $24
	.word @song0ref1013
	.byte $41, $23
	.word @song0ref1133
@song0ref1192:
	.byte $27, $85, $00, $27, $85, $00, $27, $8f, $00, $27, $85, $00, $27, $85, $00, $27, $8f, $00, $2e, $85, $00, $2e, $85, $00
	.byte $2b, $85, $00, $2b, $85, $00, $2b, $8f, $00, $93, $27, $85, $00, $27, $85, $00, $2b, $8f, $00, $27, $85, $00, $27, $85
	.byte $00, $32, $8f, $00, $2b, $85, $00, $2b, $85, $00, $2e, $8f, $00, $27, $85, $00, $27, $85, $00, $26, $8f, $00, $26, $85
	.byte $00, $26, $85, $00, $26, $8f, $00, $26, $85, $00, $26, $85, $00, $26, $8f, $00, $2d, $85, $00, $2d, $85, $00, $29, $85
	.byte $00, $29, $85, $00, $30, $8f, $00, $93, $26, $85, $00, $26, $85, $00, $29, $8f, $00, $26, $85, $00, $26, $85, $00, $30
	.byte $8f, $00, $29, $85, $00, $29, $85, $00, $2d, $8f, $00, $26, $85, $00, $26, $85, $00, $27, $8f, $00
	.byte $41, $43
	.word @song0ref1192
	.byte $41, $1e
	.word @song0ref1091
	.byte $25, $8f, $00, $93, $25, $8f, $00, $25, $8f, $00, $25, $8f, $00, $25, $9d, $00, $ad
	.byte $41, $24
	.word @song0ref1013
	.byte $41, $24
	.word @song0ref1013
	.byte $41, $24
	.word @song0ref1052
	.byte $41, $24
	.word @song0ref1052
	.byte $41, $24
	.word @song0ref1091
	.byte $41, $24
	.word @song0ref1091
	.byte $41, $24
	.word @song0ref1013
	.byte $41, $23
	.word @song0ref1133
	.byte $41, $21
	.word @song0ref1016
	.byte $41, $24
	.word @song0ref1013
	.byte $41, $24
	.word @song0ref1052
	.byte $41, $24
	.word @song0ref1052
	.byte $41, $24
	.word @song0ref1091
	.byte $41, $24
	.word @song0ref1091
	.byte $41, $24
	.word @song0ref1013
	.byte $41, $23
	.word @song0ref1133
	.byte $41, $8c
	.word @song0ref1192
	.byte $41, $43
	.word @song0ref1192
	.byte $41, $1e
	.word @song0ref1091
	.byte $25, $8f, $00, $93, $25, $8f, $00, $25, $8f, $00, $25, $8f, $00, $25, $9d, $00, $99
@song0ref1429:
	.byte $22, $91, $8b, $00, $85, $22, $85, $00, $22, $85, $00, $22, $8f, $00, $22, $85, $00, $22, $85, $00, $22, $8f, $00, $22
	.byte $85, $00, $22, $85, $00, $22, $8f, $00, $24, $9d, $00, $85, $24, $85, $00, $24, $85, $00, $24, $8f, $00, $24, $85, $00
	.byte $24, $85, $00, $24, $8f, $00, $24, $85, $00, $24, $85, $00, $24, $8f, $00, $1a, $91, $8b, $00, $85, $26, $8f, $00, $1c
	.byte $8f, $00, $28, $8f, $00, $1d, $8f, $00, $29, $8f, $00, $1c, $8f, $00, $1a, $9d, $00, $85, $26, $8f, $00, $1c, $8f, $00
	.byte $28, $8f, $00, $1d, $8f, $00, $29, $8f, $00, $1c, $8f, $00
	.byte $41, $3c
	.word @song0ref1429
	.byte $25, $9d, $00, $85, $26, $9d, $00, $85, $90, $2c, $85, $00, $2c, $85, $00, $2b, $85, $00, $2b, $85, $00, $29, $85, $00
	.byte $29, $85, $00, $27, $85, $00, $27, $85, $00, $8a, $24, $8f, $00, $26, $8f, $00, $93, $24, $8f, $00, $26, $9d, $00, $85
	.byte $24, $8f, $00, $25, $8f, $00, $26, $9d, $00, $85, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80, $21, $91, $21, $87, $21, $87
@song0ref1609:
	.byte $82, $1c, $91, $80, $21, $87, $21, $87, $21, $91, $21, $87, $21, $87, $82, $1c, $91, $80, $21, $87, $21, $87, $21, $91
	.byte $21, $87, $21, $87, $82, $1c, $91, $80, $21, $87, $21, $87, $21, $91, $21, $87, $21, $87, $82, $1c, $91, $80, $21, $87
	.byte $21, $87, $21, $91, $21, $89, $21, $85
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $30
	.word @song0ref1609
	.byte $41, $2a
	.word @song0ref1609
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1750:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $1e
	.word @song0ref1750
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $42
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $96
@song1ref6:
	.byte $25, $87, $00, $25, $87, $00, $25, $87, $00, $8b, $25, $87, $00, $23, $93, $00, $25, $e7, $00, $48, $27, $87, $00, $27
	.byte $87, $00, $27, $87, $00, $8b, $27, $87, $00, $25, $93, $00, $27, $e7, $00, $48, $28, $87, $00, $28, $87, $00, $8b, $28
	.byte $87, $00, $af, $2b, $87, $00, $2b, $87, $00, $8b, $2b, $87, $00, $af, $48, $8b, $2c, $87, $00, $8b, $2a, $89, $2a, $87
	.byte $00, $26, $87, $00, $2a, $87, $00, $2b, $87, $00, $98
@song1ref89:
	.byte $2c, $81, $00, $2d, $81, $00, $2c, $81, $00, $2d, $81, $00
	.byte $41, $09
	.word @song1ref89
	.byte $9a, $2c, $ab, $00, $85, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $9c, $1c, $87, $00, $1c, $87, $00, $1c, $87, $00, $8b, $1c, $87, $00, $1b, $93, $00, $1c, $e7, $00, $1e, $87, $00, $1e
	.byte $87, $00, $1e, $87, $00, $8b, $1e, $87, $00, $1c, $93, $00, $1e, $e7, $00, $20, $87, $00, $20, $87, $00, $8b, $20, $87
	.byte $00, $af, $22, $87, $00, $22, $87, $00, $8b, $22, $87, $00, $af, $8b, $24, $87, $00, $8b, $21, $87, $00, $21, $87, $00
	.byte $20, $87, $00, $21, $87, $00, $21, $87, $00, $9e, $27, $db, $00, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $86, $25, $db, $00, $8b
	.byte $41, $09
	.word @song1ref6
	.byte $25, $87, $00, $24, $9f, $00, $23, $db, $00, $8b, $23, $87, $00, $23, $87, $00, $23, $87, $00, $23, $87, $00, $22, $9f
	.byte $00, $21, $87, $00, $21, $87, $00, $8d, $21
@song1ref243:
	.byte $85, $00, $8b, $88, $31, $87, $00, $31, $93, $00, $86, $27, $87, $00, $27, $87, $00, $8d, $27
	.byte $41, $09
	.word @song1ref243
	.byte $a4, $20, $ff, $bd, $42
	.word @song1ch2loop
@song1ch4:
@song1ch3:
@song1ch3loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $42
	.word @song1ch3loop
