# measure_sections.cmake
# Runs at build time via: cmake -P measure_sections.cmake
#   -DREADELF=<path to llvm-readelf>
#   -DELF_FILE=<path to pass1 ELF>
#   -DOUTPUT_FILE=<path to write ca65_padding.s>
#
# Parses the .zp and .bss sections from an llvm-mos ELF to determine
# how much ZEROPAGE and BSS space the C side consumes. Writes a ca65
# assembly file with .res directives that reserve that space so
# FamiStudio (and any other ca65 code) starts AFTER the C allocations.

cmake_minimum_required(VERSION 3.18)

if(NOT DEFINED READELF OR NOT DEFINED ELF_FILE OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR
            "Usage: cmake -P measure_sections.cmake "
            "-DREADELF=<path> -DELF_FILE=<path> -DOUTPUT_FILE=<path>")
endif()

# ---- Run llvm-readelf ----
execute_process(
        COMMAND "${READELF}" -S "${ELF_FILE}"
        OUTPUT_VARIABLE SECTIONS
        ERROR_VARIABLE  READELF_ERR
        RESULT_VARIABLE READELF_RC
        OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT READELF_RC EQUAL 0)
    message(FATAL_ERROR "llvm-readelf failed: ${READELF_ERR}")
endif()

# ---- Parse .zp section (addr + size → end of llvm-mos zero page) ----
# Matches ".zp" followed by spaces then NOBITS — won't match .zp.data or .zp.bss
set(ZP_END 32)  # fallback: just past imaginary registers $00-$1F

string(REPLACE "\n" ";" LINES "${SECTIONS}")
foreach(LINE ${LINES})
    if(LINE MATCHES "\\.zp[ ]+NOBITS[ ]+([0-9a-fA-F]+)[ ]+[0-9a-fA-F]+[ ]+([0-9a-fA-F]+)")
        set(ZP_ADDR "${CMAKE_MATCH_1}")
        set(ZP_SIZE "${CMAKE_MATCH_2}")
        math(EXPR ZP_END "0x${ZP_ADDR} + 0x${ZP_SIZE}")
    endif()
endforeach()

# Align to 2-byte boundary (imaginary registers are 2-byte pairs)
math(EXPR ZP_REMAINDER "${ZP_END} % 2")
if(NOT ZP_REMAINDER EQUAL 0)
    math(EXPR ZP_END "${ZP_END} + 1")
endif()

# ---- Parse .bss section ----
set(BSS_RESERVE 0)

foreach(LINE ${LINES})
    if(LINE MATCHES "\\.bss[ ]+NOBITS[ ]+([0-9a-fA-F]+)[ ]+[0-9a-fA-F]+[ ]+([0-9a-fA-F]+)")
        set(BSS_ADDR "${CMAKE_MATCH_1}")
        set(BSS_SIZE "${CMAKE_MATCH_2}")
        math(EXPR BSS_RESERVE "0x${BSS_SIZE}")
    endif()
endforeach()

# ---- Report ----
message(STATUS "ZP reserve: ${ZP_END} bytes (past llvm-mos registers + .zp)")
if(BSS_RESERVE GREATER 0)
    message(STATUS "BSS reserve: ${BSS_RESERVE} bytes")
else()
    message(STATUS "BSS reserve: none needed")
endif()

# ---- Write padding file ----
set(PADDING_CONTENT
        "; Auto-generated by measure_sections.cmake — do not edit
; Reserves space so ca65 ZEROPAGE/BSS allocations start after
; llvm-mos imaginary registers and C variables.
;
; ZP end:      $${ZP_ADDR} + $${ZP_SIZE} = ${ZP_END} bytes
; BSS reserve: ${BSS_RESERVE} bytes
;
.segment \"ZEROPAGE\"
.res ${ZP_END}
        ")

if(BSS_RESERVE GREATER 0)
    string(APPEND PADDING_CONTENT
            ".segment \"BSS\"
.res ${BSS_RESERVE}
            ")
endif()

file(WRITE "${OUTPUT_FILE}" "${PADDING_CONTENT}")
message(STATUS "Wrote ${OUTPUT_FILE}")